name: VivianRosenthal
favicon: null
layout_spectrum: 0.32894
typography_spectrum: 0.93745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebfbff'
    - '#cbd6e0'
    - '#213049'
    - '#426570'
    - '#90a8ae'
  brandStrength: 0.75
  lightness: 0.8014533189125359
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
